# Numpy
* NumPy is a general-purpose array-processing package.
* Numpy was created to work with multidmensional arrays.
* It is the fundamental package for scientific computing with Python.
* It is open-source library

# Why Use NumPy?
* In Python we have lists that serve the purpose of arrays, but they are slow to process.
* NumPy aims to provide an array object that is up to 50x faster than traditional Python lists.
* The array object in NumPy is called ndarray, it provides a lot of supporting functions that make working with ndarray very easy.
* Arrays are very frequently used in data science, where speed and resources are very important.

In [5]:
! pip install numpy

In [4]:
#Importing necessary library
import numpy as np

In [6]:
# Array creation
a=np.array(10)
type(a)

numpy.ndarray

In [7]:
# Zero dimesional array -(single point)

In [9]:
z=np.array(10)

z.ndim

0

In [10]:
# One dimesional array

In [18]:
o=np.array([10,11,12])

o.ndim

1

In [ ]:
# Two dimensional array

In [20]:
t=np.array([[10,11,12,13,13]])

t.ndim

2

In [16]:
# Three dimensional array

In [22]:
th=np.array([[[10,12,24,25]]])

th.ndim

3

In [23]:
#Change the data type of the array elements.

In [26]:
a=np.array([10,11,12,13])

a.dtype

dtype('int32')

In [35]:
a=np.array([10,11,12,14], dtype='float')
# when we print all data then every time type the print()
print(a.dtype)
print('Hello')
# It will be converted into float number
a

float64
Hello


array([10., 11., 12., 14.])

# Other ways of creating an array
1. arange
2. linspace
3. zeros
4. ones
5. random

In [38]:
# Arange- it's arrange sequensliy 
a=np.arange(1,21)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [40]:
a=np.arange(1,21,2)
a

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [47]:
a=np.arange(2,21,2)

a

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [32]:
# It wii be converted into float number
a

array([10., 11., 12., 14.])

In [48]:
# linespace- Evenly spaced vaules 

b= np.linspace(1,5,15, retstep=True)
b

In [58]:
# Zeros- its shows rows and columns(shape)

In [62]:
z= np.zeros([2,2])
z

array([[0., 0.],
       [0., 0.]])

In [64]:
o=np.ones([5,5])
o

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [65]:
# random - To take any rows and columns whateveryou want

In [67]:
r=np.random.rand(5,5)
r

array([[0.12293578, 0.66404476, 0.97962352, 0.46618668, 0.43648498],
       [0.15291941, 0.6229416 , 0.80152396, 0.05518145, 0.70200822],
       [0.30903642, 0.08215586, 0.49435447, 0.99045617, 0.40491047],
       [0.93028578, 0.35674614, 0.68629314, 0.59527509, 0.18223106],
       [0.91977524, 0.83944376, 0.41083925, 0.81966523, 0.49432956]])

In [69]:
# it's take random values who gives number and inbetween size.
r=np.random.randint(5,size=10)
r

array([3, 3, 2, 1, 0, 3, 2, 1, 0, 1])

# Slicing and Indexing of arrays

In [73]:
a= np.array([[1,2,3], [4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [74]:
a.ndim

2

In [75]:
#print 1
a[0,0]

1

In [77]:
# print 6
a[1,2]

6

In [78]:
# print 2 and 3 
a[0,1:]

array([2, 3])

In [83]:
# print 2,3 and 5,6
a[0:,1:]

array([[2, 3],
       [5, 6]])

In [84]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [85]:
# 1 and 6
a[[0,1],[0,2]]

array([1, 6])

In [86]:
# 3 and 4
a[[0,1],[2,0]]

array([3, 4])

# Reshaping the arrays 
Shape means number of rows and number cloumns

In [88]:
a=np.random.rand(5,2)
a

array([[0.73690183, 0.04285497],
       [0.89126057, 0.90362136],
       [0.13091291, 0.48998694],
       [0.10337683, 0.26486596],
       [0.61079592, 0.47776782]])

In [89]:
a.reshape(2,5)

array([[0.73690183, 0.04285497, 0.89126057, 0.90362136, 0.13091291],
       [0.48998694, 0.10337683, 0.26486596, 0.61079592, 0.47776782]])

In [90]:
a.reshape(10,1)

array([[0.73690183],
       [0.04285497],
       [0.89126057],
       [0.90362136],
       [0.13091291],
       [0.48998694],
       [0.10337683],
       [0.26486596],
       [0.61079592],
       [0.47776782]])

In [91]:
a.reshape(1,10)

array([[0.73690183, 0.04285497, 0.89126057, 0.90362136, 0.13091291,
        0.48998694, 0.10337683, 0.26486596, 0.61079592, 0.47776782]])

In [92]:
# we are not sure what is put in rows / columns then put (-1) in only rows as wll as columns. 
# don't put both rows and columns because it will gives error. .
a.reshape(5,-1)

array([[0.73690183, 0.04285497],
       [0.89126057, 0.90362136],
       [0.13091291, 0.48998694],
       [0.10337683, 0.26486596],
       [0.61079592, 0.47776782]])

In [93]:
a.reshape(-1,5)

array([[0.73690183, 0.04285497, 0.89126057, 0.90362136, 0.13091291],
       [0.48998694, 0.10337683, 0.26486596, 0.61079592, 0.47776782]])

# Aggregate Functions
* The Python numpy aggregate functions are sum, min, max, mean, average, product, median, standard deviation, variance, percentile, and corrcoef.


In [94]:
a

array([[0.73690183, 0.04285497],
       [0.89126057, 0.90362136],
       [0.13091291, 0.48998694],
       [0.10337683, 0.26486596],
       [0.61079592, 0.47776782]])

In [95]:
a.min()

0.04285497347395206

In [96]:
a.std()

0.30507477722963133

In [97]:
a.mean()

0.4652345114408969

In [98]:
a.var()

0.09307061970170917

# Stacking
* Stacking is used to join 2 different arrays.
1. Vertical stacking
2. Horizontal stacking

In [101]:
a=np.array([1,2,3,4,5])
b=np.array([4,5,6,7,8])

In [102]:
np.hstack([a,b])

array([1, 2, 3, 4, 5, 4, 5, 6, 7, 8])

In [103]:
np.vstack([a,b])

array([[1, 2, 3, 4, 5],
       [4, 5, 6, 7, 8]])

In [104]:
np.hstack([b,a])

array([4, 5, 6, 7, 8, 1, 2, 3, 4, 5])